production:
  access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['S3_ACCESS_KEY'] %>
  bucket: 'garden-redmine'
  endpoint:
  secure:
  private:
  expires: 
  proxy:

development:
  access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['S3_ACCESS_KEY'] %>
  bucket: 'garden-redmine'
  endpoint:
  secure:
  private:
  expires: 
  proxy:
